#!/bin/bash
#

TARGET=..
VERSION=0.1
RELEASE_DIR=$TARGET/ibrdtn-$VERSION

echo "copy prerequisits"
mkdir $RELEASE_DIR
cp configure.in $RELEASE_DIR/
cp Makefile.in-release $RELEASE_DIR/Makefile.in

# copy include
echo "copy include"
cp -R include/ $RELEASE_DIR/
rm -rf $RELEASE_DIR/include/testsuite
rm $RELEASE_DIR/include/config.h

# copy source
echo "copy source"
cp -R src/ $RELEASE_DIR/
rm -rf $RELEASE_DIR/src/testsuite

# copy default database
echo "copy default database"
cp database-clean.db $RELEASE_DIR/database.db

# copy doxygen
echo "doxygen"
cp ibrdtn.doxygen $RELEASE_DIR/

# copy default config
echo "default config"
mkdir $RELEASE_DIR/etc
cp etc/config.ini $RELEASE_DIR/etc/default.ini

# run autoconf
echo "run autoconf"
cd $RELEASE_DIR/
autoconf --include=include
rm configure.in
rm -rf autom4te.cache

# remove all .svn directories
echo "remove all .svn directories"
rm -rf `find . -name .svn`

# make a archive
echo "make a archive"
tar czf ../ibrdtn-$VERSION.tar.gz ./

